### PR TITLE
move js to ecma to avoid jsx problems

### PR DESCRIPTION
**Pull request by elgiano**
Issue #3 is probably due to https://github.com/nvim-treesitter/nvim-treesitter/commit/69a55e86cebec679f26b0d1fda28bb0359d6dd64

Note also this previous commit https://github.com/nvim-treesitter/nvim-treesitter/commit/3b8c2ea492917fcb3c0e88ad6682dbd355cc0644 message:
> create ecma base for use in js and ts which fixes jsx issues

Typescript injections should not import `javascript`, which pulls `jsx`, but `ecma`.
So I moved `javascript` injections to `ecma`, and I removed the typescript injections all together, since they already inherit from ecma.

### CODE REVIEW

**Comment by kohane27** [comment]
Thank you so much! Can confirm that your solution works perfectly.
Was blind without syntax highlighting from the inline templates and styles but now no more!
Much appreciated!

**Comment by kohane27** [comment]
If someone is still struggling with this error, I can confirm that @elgiano  solution works.
If you're using packer:

```
  use({ "elgiano/nvim-treesitter-angular", branch = "topic/jsx-fix" })
```

Thank you elgiano again!

**Comment by kjbetz** [comment]
Hi, @elgiano and @kohane27!

Thanks for fixing this!

Is there anything I need to do to get it working properly? I installed this branch... my inline templates are still not being highlighted. Any gotcha's I need to have set up with nvim-treesitter?

Thanks!

**Comment by kohane27** [comment]
@kjbetz  If you were using packer:

```lua
use({ "elgiano/nvim-treesitter-angular", branch = "topic/jsx-fix" })
```

the run `:TSUpdate` to see if it works.

**Comment by kjbetz** [comment]
@kohane27, thanks for the reply!

I just figured out I had an issue with the html parser being compiled and installed correctly. I fixed that and now I have inline template highlighting working.

Thanks to you both!

**Comment by osenvosem** [comment]
@steelsojka could you merge this please?

**Comment by zapling** [comment]
Can confirm that this fix still works as expected

**Comment by jigfox** [comment]
what needs to be done, to get this merged?

**Pull request merged**
